name: CD Build

on:
    workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  #   paths-ignore:
  #     - "**.md"
  #     - '**/*.gitignore'
  #     - '**/*.gitattributes'
  #     - '**/*.yml'
  # pull_request:
  #   branches: [ "main" ]

jobs:
    build-backend:
        runs-on: windows-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install .NET 9
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 9.0

          - name: Install .NET MAUI Workload
            run: dotnet workload install maui

          - name: Build backend
            run: dotnet publish ./MauiWithBackend.Backend/MauiWithBackend.Backend.csproj -o release/backend/ --sc

          - name: Upload backend
            uses: actions/upload-artifact@v4
            with:
                name: maui-backend
                if-no-files-found: error
                path: release/backend/

          - name: Build frontend
            run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj -o release/frontend/ --sc

          - name: Upload frontend
            uses: actions/upload-artifact@v4
            with:
                name: maui-frontend
                if-no-files-found: error
                path: release/frontend/

    # build-frontend:
    #     name: Build ${{ matrix.os }}
    #     permissions:
    #         contents: write
    #     strategy:
    #         matrix:
    #             os: [ windows-latest, macos-15 ]
    #     runs-on: ${{ matrix.os }}

    #     steps:
    #       - name: Checkout code
    #         uses: actions/checkout@v4

    #       - name: Install .NET 9
    #         uses: actions/setup-dotnet@v4
    #         with:
    #             dotnet-version: 9.0

    #       - name: Install .NET MAUI Workload
    #         run: dotnet workload install maui

    #       - name: Select Xcode Version
    #         run: sudo xcode-select -s /Applications/Xcode_16.2.app
    #         if: runner.os == 'macOS'

    #       - name: Build
    #         run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj
