name: Build

on:
    workflow_dispatch:

jobs:
    build-backend:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
            - run: dotnet workload install maui

            - run: dotnet publish ./MauiWithBackend.Backend/MauiWithBackend.Backend.csproj -o release/ --sc
            - uses: actions/upload-artifact@v4
              with:
                name: maui-backend
                if-no-files-found: error
                path: release/

    build-frontend-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                framework: [net9.0-android, net9.0-windows10.0.19041.0]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
            - run: dotnet workload install maui

            - run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj -o release/ --sc -f ${{ matrix.framework }}
            - uses: actions/upload-artifact@v4
              with:
                name: maui-frontend-${{ matrix.framework }}
                if-no-files-found: error
                path: release/

    build-frontend-macos:
        runs-on: macos-15
        strategy:
            matrix:
                framework: [net9.0-maccatalyst] # net9.0-ios

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
            - run: dotnet workload install maui
            - run: sudo xcode-select -s /Applications/Xcode_16.2.app

            - run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj -o release/ --sc -f ${{ matrix.framework }}
            - uses: actions/upload-artifact@v4
              with:
                name: maui-frontend-${{ matrix.framework }}
                if-no-files-found: error
                path: release/
