name: Build

on:
    workflow_dispatch:

jobs:
    build-backend:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
                cache: true
            - run: dotnet workload install maui

            - run: dotnet publish ./MauiWithBackend.Backend/MauiWithBackend.Backend.csproj -o release/ --sc
            - uses: actions/upload-artifact@v4
              with:
                name: maui-backend
                if-no-files-found: error
                path: release/

    build-frontend-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                framework: [net9.0-android, net9.0-windows10.0.19041.0]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0
                cache: true
            - run: dotnet workload install maui

            - run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj -o release/ --sc -f ${{ matrix.framework }}
            - uses: actions/upload-artifact@v4
              with:
                name: maui-frontend-${{ matrix.framework }}
                if-no-files-found: error
                path: release/

    # build-frontend:
    #     name: Build ${{ matrix.os }}
    #     permissions:
    #         contents: write
    #     strategy:
    #         matrix:
    #             os: [ windows-latest, macos-15 ]
    #     runs-on: ${{ matrix.os }}

    #     steps:
    #       - name: Checkout code
    #         uses: actions/checkout@v4

    #       - name: Install .NET 9
    #         uses: actions/setup-dotnet@v4
    #         with:
    #             dotnet-version: 9.0

    #       - name: Install .NET MAUI Workload
    #         run: dotnet workload install maui

    #       - name: Select Xcode Version
    #         run: sudo xcode-select -s /Applications/Xcode_16.2.app
    #         if: runner.os == 'macOS'

    #       - name: Build
    #         run: dotnet publish ./MauiWithBackend.Frontend/MauiWithBackend.Frontend.csproj
